# Generated by Django 5.2.16 on 2026-07-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuprequest',
            name='clothes_image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
    ]
