# Generated by Django 5.2.16 on 2026-08-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_makeuprequest_analysis_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupStepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='makeup_steps/')),
                ('arrow_target', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makeup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_images', to='analysis.makeuprequest')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
